version: '3.7'
services:
  postgres:
    environment:
      POSTGRES_USER: tm41m
      POSTGRES_PASSWORD: tm41m
      POSTGRES_DB: tm41m
    image: postgis/postgis:12-3.4
    restart: always
    ports:
      - "1255:5432"
  dbt:
    image: thecartercodes/postgis-dbt:0.1
    volumes:
      - ./healthcare_metrics/:/usr/app
      - ./healthcare_metrics/profiles.yml:/root/.dbt/profiles.yml
      - ./scripts/bootstrap.sh:/usr/app/scripts/bootstrap.sh
      - ./migrations/:/usr/app/migrations
    command: /usr/app/scripts/bootstrap.sh
    links:
      - postgres
    depends_on:
      - postgres
