healthcare_metrics:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 1255
      user: tm41m
      pass: tm41m
      dbname: tm41m
      schema: wolfram

  target: dev
